require: rubocop-rspec

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'
    - 'spec/system/**'
    - 'node_modules/**/*'
    - 'tmp/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/books_spec.rb'

Layout/LineLength:
  Exclude:
    - 'db/seeds.rb'
  