default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["lando_booktrade_database_conn_host"] || "localhost" %>
  port: <%= ENV["lando_booktrade_database_conn_port"] || 5432 %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: booktrade_development

test:
  <<: *default
  database: booktrade_test

production:
  <<: *default